const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await ethers.provider.getBalance(deployer.address)).toString());

  // 1. Deploy ProductRegistry
  console.log("\n[1/3] Deploying ProductRegistry...");
  const ProductRegistry = await ethers.getContractFactory("ProductRegistry");
  const productRegistry = await ProductRegistry.deploy();
  await productRegistry.waitForDeployment();
  const productRegistryAddress = await productRegistry.getAddress();
  console.log("ProductRegistry deployed to:", productRegistryAddress);

  // 2. Deploy SellerRegistry
  console.log("\n[2/3] Deploying SellerRegistry...");
  const SellerRegistry = await ethers.getContractFactory("SellerRegistry");
  const sellerRegistry = await SellerRegistry.deploy();
  await sellerRegistry.waitForDeployment();
  const sellerRegistryAddress = await sellerRegistry.getAddress();
  console.log("SellerRegistry deployed to:", sellerRegistryAddress);

  // 3. Deploy SupplyChain (depends on the two above)
  console.log("\n[3/3] Deploying SupplyChain...");
  const SupplyChain = await ethers.getContractFactory("SupplyChain");
  const supplyChain = await SupplyChain.deploy(productRegistryAddress, sellerRegistryAddress);
  await supplyChain.waitForDeployment();
  const supplyChainAddress = await supplyChain.getAddress();
  console.log("SupplyChain deployed to:", supplyChainAddress);

  // ── Write addresses directly into frontend .env ──────────────────────────
  const frontendEnvPath = path.join(__dirname, "../../fake-product-identification/.env");
  const envContent = `# Auto-generated by deploy script — do not edit manually
VITE_PRODUCT_REGISTRY_ADDRESS=${productRegistryAddress}
VITE_SELLER_REGISTRY_ADDRESS=${sellerRegistryAddress}
VITE_SUPPLY_CHAIN_ADDRESS=${supplyChainAddress}
VITE_CHAIN_ID=11155111
`;
  fs.writeFileSync(frontendEnvPath, envContent);
  console.log("\n✅ Frontend .env updated automatically:", frontendEnvPath);

  console.log("\n✅ Deployment complete!");
  console.log("─────────────────────────────────────────");
  console.log("ProductRegistry :", productRegistryAddress);
  console.log("SellerRegistry  :", sellerRegistryAddress);
  console.log("SupplyChain     :", supplyChainAddress);
  console.log("─────────────────────────────────────────");
  console.log("Update your frontend .env with these addresses.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
